# Generated by Django 5.1.4 on 2025-02-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_group_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
