# Generated by Django 5.1.4 on 2025-02-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='option',
            field=models.CharField(choices=[('Funcionário', 'funcionário'), ('Gerente', 'gerente'), ('Chefe', 'Chefe')], default='FUNCIONARIO', max_length=20),
        ),
    ]
