# Generated by Django 5.1.4 on 2025-02-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usergroup_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.CharField(choices=[('FUNCIONARIO', 'Funcionário'), ('GERENTE', 'Gerente'), ('CHEFE', 'Chefe')], default='FUNCIONARIO', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
