# Generated by Django 5.1.4 on 2025-02-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_group_delete_usergroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='group',
            new_name='option',
        ),
    ]
