# Generated by Django 5.1.4 on 2025-02-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='option',
            field=models.CharField(choices=[('Funcionário', 'Funcionário'), ('Gerente', 'Gerente'), ('Chefe', 'Chefe')], max_length=20),
        ),
    ]
