# Generated by Django 5.1.4 on 2025-02-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='option',
            field=models.CharField(choices=[('FUNCIONARIO', 'Funcionário'), ('GERENTE', 'Gerente'), ('CHEFE', 'Chefe')], default='FUNCIONARIO', max_length=20),
        ),
    ]
